name: PHP

on:
  push:
    tags:
    - '*'
  pull_request:
    branches: [main]

jobs:

  build-php:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: composer update --no-progress

    - name: Test
      run: php vendor/bin/phpunit .
